/*
 * This file was automatically generated by EvoSuite
 * Mon Sep 21 15:15:09 GMT 2026
 */

package com.fasterxml.jackson.databind.type;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.fasterxml.jackson.annotation.ObjectIdResolver;
import com.fasterxml.jackson.core.JsonFactory;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.AnnotationIntrospector;
import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.JavaType;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.ObjectReader;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.databind.introspect.TypeResolutionContext;
import com.fasterxml.jackson.databind.jsontype.impl.ClassNameIdResolver;
import com.fasterxml.jackson.databind.module.SimpleModule;
import com.fasterxml.jackson.databind.node.TextNode;
import com.fasterxml.jackson.databind.type.ArrayType;
import com.fasterxml.jackson.databind.type.ClassStack;
import com.fasterxml.jackson.databind.type.CollectionLikeType;
import com.fasterxml.jackson.databind.type.CollectionType;
import com.fasterxml.jackson.databind.type.MapLikeType;
import com.fasterxml.jackson.databind.type.MapType;
import com.fasterxml.jackson.databind.type.ReferenceType;
import com.fasterxml.jackson.databind.type.ResolvedRecursiveType;
import com.fasterxml.jackson.databind.type.SimpleType;
import com.fasterxml.jackson.databind.type.TypeBase;
import com.fasterxml.jackson.databind.type.TypeBindings;
import com.fasterxml.jackson.databind.type.TypeFactory;
import com.fasterxml.jackson.databind.type.TypeModifier;
import com.fasterxml.jackson.databind.type.TypeParser;
import java.lang.reflect.Array;
import java.lang.reflect.GenericArrayType;
import java.lang.reflect.ParameterizedType;
import java.lang.reflect.Type;
import java.util.Collection;
import java.util.EnumSet;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import java.util.Stack;
import java.util.TreeSet;
import java.util.concurrent.atomic.AtomicReference;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.System;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TypeFactory_ESTest extends TypeFactory_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ObjectMapper objectMapper0 = new ObjectMapper();
      TreeSet<MapLikeType> treeSet0 = new TreeSet<MapLikeType>();
      ObjectReader objectReader0 = objectMapper0.readerForUpdating(treeSet0);
      assertNotNull(objectReader0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.instance;
      Class<String> class0 = String.class;
      Class<SerializationFeature> class1 = SerializationFeature.class;
      Stack<JavaType> stack0 = new Stack<JavaType>();
      TypeBindings typeBindings0 = TypeBindings.create((Class<?>) class1, (List<JavaType>) stack0);
      JavaType[] javaTypeArray0 = typeFactory0._resolveSuperInterfaces((ClassStack) null, class0, typeBindings0);
      assertEquals(3, javaTypeArray0.length);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      System.setCurrentTimeMillis((-636L));
      TypeFactory typeFactory0 = TypeFactory.instance;
      TypeParser typeParser0 = new TypeParser(typeFactory0);
      ClassLoader classLoader0 = ClassLoader.getSystemClassLoader();
      classLoader0.getParent();
      classLoader0.setDefaultAssertionStatus(true);
      classLoader0.setClassAssertionStatus("char", true);
      TypeParser.MyTokenizer typeParser_MyTokenizer0 = new TypeParser.MyTokenizer("char");
      typeParser0.parseType(typeParser_MyTokenizer0);
      Class<DeserializationFeature> class0 = DeserializationFeature.class;
      Class<Properties> class1 = Properties.class;
      Class<ArrayType> class2 = ArrayType.class;
      Class<MapType> class3 = MapType.class;
      Class<String> class4 = String.class;
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ObjectMapper objectMapper0 = new ObjectMapper();
      Class<MapType> class0 = MapType.class;
      ObjectReader objectReader0 = objectMapper0.readerFor(class0);
      assertNotNull(objectReader0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.defaultInstance();
      Class<TextNode> class0 = TextNode.class;
      TypeBindings typeBindings0 = TypeFactory.EMPTY_BINDINGS;
      byte[] byteArray0 = new byte[2];
      byteArray0[0] = (byte)18;
      byteArray0[1] = (byte)115;
      FileSystemHandling.appendDataToFile((EvoSuiteFile) null, byteArray0);
      typeFactory0.constructType((Type) class0);
      typeFactory0._findPrimitive("double");
      System.setCurrentTimeMillis((-1L));
      Class<CollectionLikeType> class1 = CollectionLikeType.class;
      ClassStack classStack0 = new ClassStack(class1);
      Class<MapLikeType> class2 = MapLikeType.class;
      ClassStack classStack1 = classStack0.child(class2);
      classStack1.find(class2);
      Class<?> class3 = typeFactory0._findPrimitive("property-based");
      assertNull(class3);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.instance;
      Class<SerializationFeature> class0 = SerializationFeature.class;
      JavaType[] javaTypeArray0 = new JavaType[10];
      Class<MapLikeType> class1 = MapLikeType.class;
      TypeBindings typeBindings0 = TypeBindings.createIfNeeded(class1, javaTypeArray0);
      TypeResolutionContext.Basic typeResolutionContext_Basic0 = new TypeResolutionContext.Basic(typeFactory0, typeBindings0);
      JavaType javaType0 = typeResolutionContext_Basic0.resolveType(class0);
      javaTypeArray0[0] = javaType0;
      TypeModifier typeModifier0 = mock(TypeModifier.class, new ViolatedAssumptionAnswer());
      doReturn(javaTypeArray0[0], javaType0).when(typeModifier0).modifyType(any(com.fasterxml.jackson.databind.JavaType.class) , any(java.lang.reflect.Type.class) , any(com.fasterxml.jackson.databind.type.TypeBindings.class) , any(com.fasterxml.jackson.databind.type.TypeFactory.class));
      TypeFactory typeFactory1 = typeFactory0.withModifier(typeModifier0);
      MapLikeType mapLikeType0 = typeFactory1.constructRawMapLikeType(class0);
      assertTrue(mapLikeType0.isFinal());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.instance;
      Class<SerializationFeature> class0 = SerializationFeature.class;
      TypeModifier typeModifier0 = mock(TypeModifier.class, new ViolatedAssumptionAnswer());
      doReturn((JavaType) null).when(typeModifier0).modifyType(any(com.fasterxml.jackson.databind.JavaType.class) , any(java.lang.reflect.Type.class) , any(com.fasterxml.jackson.databind.type.TypeBindings.class) , any(com.fasterxml.jackson.databind.type.TypeFactory.class));
      doReturn((String) null).when(typeModifier0).toString();
      TypeFactory typeFactory1 = typeFactory0.withModifier(typeModifier0);
      // Undeclared exception!
      try { 
        typeFactory1.constructRawMapLikeType(class0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // TypeModifier null (of type com.fasterxml.jackson.databind.type.TypeModifier$MockitoMock$253586958) return null for type [simple type, class java.lang.Enum]
         //
         verifyException("com.fasterxml.jackson.databind.type.TypeFactory", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.instance;
      TypeParser typeParser0 = new TypeParser(typeFactory0);
      TypeModifier[] typeModifierArray0 = new TypeModifier[0];
      TypeFactory typeFactory1 = new TypeFactory(typeParser0, typeModifierArray0);
      Class<Object> class0 = Object.class;
      JavaType javaType0 = typeFactory1.constructSimpleType(class0, (JavaType[]) null);
      Class<SimpleType> class1 = SimpleType.class;
      JavaType javaType1 = typeFactory1.constructSpecializedType(javaType0, class1);
      assertFalse(javaType1.isJavaLangObject());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.defaultInstance();
      Class<Object> class0 = Object.class;
      ClassStack classStack0 = new ClassStack(class0);
      TypeBindings typeBindings0 = TypeBindings.emptyBindings();
      GenericArrayType genericArrayType0 = mock(GenericArrayType.class, new ViolatedAssumptionAnswer());
      doReturn((Type) null).when(genericArrayType0).getGenericComponentType();
      Type[] typeArray0 = new Type[5];
      typeArray0[0] = (Type) genericArrayType0;
      ParameterizedType parameterizedType0 = mock(ParameterizedType.class, new ViolatedAssumptionAnswer());
      doReturn(typeArray0).when(parameterizedType0).getActualTypeArguments();
      doReturn(typeArray0[2]).when(parameterizedType0).getRawType();
      // Undeclared exception!
      try { 
        typeFactory0._fromParamType(classStack0, parameterizedType0, typeBindings0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unrecognized Type: [null]
         //
         verifyException("com.fasterxml.jackson.databind.type.TypeFactory", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.instance;
      Class<SerializationFeature> class0 = SerializationFeature.class;
      Class<Object> class1 = Object.class;
      JavaType[] javaTypeArray0 = new JavaType[10];
      Class<MapLikeType> class2 = MapLikeType.class;
      TypeBindings typeBindings0 = TypeBindings.createIfNeeded(class2, javaTypeArray0);
      TypeResolutionContext.Basic typeResolutionContext_Basic0 = new TypeResolutionContext.Basic(typeFactory0, typeBindings0);
      JavaType javaType0 = typeResolutionContext_Basic0.resolveType(class0);
      JavaType javaType1 = typeFactory0._constructSimple(class1, typeBindings0, javaType0, javaTypeArray0);
      assertFalse(javaType1.isEnumType());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      TypeParser typeParser0 = mock(TypeParser.class, new ViolatedAssumptionAnswer());
      doReturn((TypeParser) null).when(typeParser0).withFactory(any(com.fasterxml.jackson.databind.type.TypeFactory.class));
      TypeFactory typeFactory0 = new TypeFactory(typeParser0, (TypeModifier[]) null);
      Class<EnumSet> class0 = EnumSet.class;
      SimpleType simpleType0 = TypeFactory.CORE_TYPE_STRING;
      TypeBindings typeBindings0 = TypeBindings.createIfNeeded((Class<?>) class0, (JavaType) simpleType0);
      JavaType[] javaTypeArray0 = new JavaType[1];
      JavaType javaType0 = typeFactory0._constructSimple(class0, typeBindings0, simpleType0, javaTypeArray0);
      assertEquals(1, javaType0.containedTypeCount());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      JsonFactory jsonFactory0 = new JsonFactory();
      JsonFactory.Feature jsonFactory_Feature0 = JsonFactory.Feature.CANONICALIZE_FIELD_NAMES;
      JsonFactory jsonFactory1 = jsonFactory0.configure(jsonFactory_Feature0, false);
      ObjectMapper objectMapper0 = new ObjectMapper(jsonFactory1);
      jsonFactory0.copy();
      AtomicReference<Integer> atomicReference0 = new AtomicReference<Integer>();
      ObjectReader objectReader0 = objectMapper0.readerForUpdating(atomicReference0);
      DeserializationFeature deserializationFeature0 = DeserializationFeature.READ_DATE_TIMESTAMPS_AS_NANOSECONDS;
      DeserializationFeature[] deserializationFeatureArray0 = new DeserializationFeature[4];
      DeserializationFeature deserializationFeature1 = DeserializationFeature.UNWRAP_SINGLE_VALUE_ARRAYS;
      deserializationFeatureArray0[0] = deserializationFeature1;
      deserializationFeatureArray0[1] = deserializationFeature0;
      DeserializationFeature deserializationFeature2 = DeserializationFeature.UNWRAP_SINGLE_VALUE_ARRAYS;
      int int0 = (-488);
      Integer integer0 = new Integer((-488));
      Integer.getInteger("JSON", (-488));
      atomicReference0.compareAndSet(integer0, (Integer) null);
      deserializationFeatureArray0[2] = deserializationFeature2;
      deserializationFeatureArray0[3] = deserializationFeature0;
      objectMapper0.reader(deserializationFeature0, deserializationFeatureArray0);
      TypeFactory typeFactory0 = objectReader0.getTypeFactory();
      Class<AnnotationIntrospector.ReferenceProperty.Type> class0 = AnnotationIntrospector.ReferenceProperty.Type.class;
      ArrayType arrayType0 = typeFactory0.constructArrayType(class0);
      ClassNameIdResolver classNameIdResolver0 = new ClassNameIdResolver(arrayType0, typeFactory0);
      ArrayType arrayType1 = arrayType0.withTypeHandler(classNameIdResolver0);
      // Undeclared exception!
      try { 
        typeFactory0.constructGeneralizedType(arrayType1, class0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Class com.fasterxml.jackson.databind.AnnotationIntrospector$ReferenceProperty$Type not a super-type of [array type, component type: [simple type, class com.fasterxml.jackson.databind.AnnotationIntrospector$ReferenceProperty$Type]]
         //
         verifyException("com.fasterxml.jackson.databind.type.TypeFactory", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.defaultInstance();
      Class<SimpleModule> class0 = SimpleModule.class;
      Class<MapperFeature>[] classArray0 = (Class<MapperFeature>[]) Array.newInstance(Class.class, 1);
      Class<MapperFeature> class1 = MapperFeature.class;
      classArray0[0] = class1;
      // Undeclared exception!
      try { 
        typeFactory0.constructParametricType(class0, classArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Can not create TypeBindings for class com.fasterxml.jackson.databind.module.SimpleModule with 1 type parameter: class expects 0
         //
         verifyException("com.fasterxml.jackson.databind.type.TypeBindings", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      SimpleType simpleType0 = TypeFactory.CORE_TYPE_BOOL;
      TypeFactory typeFactory0 = TypeFactory.instance;
      Class<Properties> class0 = Properties.class;
      MapLikeType mapLikeType0 = typeFactory0.constructMapLikeType((Class<?>) class0, (JavaType) null, (JavaType) simpleType0);
      assertFalse(mapLikeType0.isAbstract());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.defaultInstance();
      Class<String> class0 = String.class;
      Class<ObjectIdResolver> class1 = ObjectIdResolver.class;
      // Undeclared exception!
      try { 
        typeFactory0.constructMapType((Class<? extends Map>) null, class0, class1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.fasterxml.jackson.databind.type.TypeBindings$TypeParamStash", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.defaultInstance();
      Class<Byte> class0 = Byte.TYPE;
      JavaType javaType0 = typeFactory0.constructType((Type) class0, (JavaType) null);
      assertFalse(javaType0.isMapLikeType());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.instance;
      SimpleType simpleType0 = TypeFactory.CORE_TYPE_OBJECT;
      // Undeclared exception!
      try { 
        typeFactory0.constructType((Type) null, (JavaType) simpleType0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unrecognized Type: [null]
         //
         verifyException("com.fasterxml.jackson.databind.type.TypeFactory", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.instance;
      Class<CollectionLikeType> class0 = CollectionLikeType.class;
      JavaType javaType0 = typeFactory0.constructType((Type) class0, (Class<?>) null);
      assertFalse(javaType0.isArrayType());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.instance;
      Class<MapperFeature> class0 = MapperFeature.class;
      TypeBindings typeBindings0 = TypeBindings.createIfNeeded(class0, (JavaType) null);
      ResolvedRecursiveType resolvedRecursiveType0 = new ResolvedRecursiveType(class0, typeBindings0);
      JavaType javaType0 = typeFactory0.constructType((Type) resolvedRecursiveType0, (Class<?>) class0);
      assertEquals(0, javaType0.containedTypeCount());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.defaultInstance();
      JavaType javaType0 = TypeFactory.unknownType();
      Class<SimpleModule> class0 = SimpleModule.class;
      TypeBindings typeBindings0 = TypeBindings.createIfNeeded(class0, javaType0);
      JavaType[] javaTypeArray0 = new JavaType[9];
      javaTypeArray0[1] = javaType0;
      MapType mapType0 = MapType.construct(class0, typeBindings0, javaType0, javaTypeArray0, javaType0, javaTypeArray0[1]);
      typeFactory0.moreSpecificType(javaType0, mapType0);
      assertTrue(javaType0.isJavaLangObject());
      assertFalse(javaType0.isPrimitive());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.instance;
      SimpleType simpleType0 = TypeFactory.CORE_TYPE_LONG;
      ReferenceType referenceType0 = ReferenceType.upgradeFrom(simpleType0, simpleType0);
      SimpleType simpleType1 = TypeFactory.CORE_TYPE_STRING;
      JavaType javaType0 = typeFactory0.moreSpecificType(referenceType0, simpleType1);
      assertFalse(javaType0.isEnumType());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.instance;
      Class<SimpleModule> class0 = SimpleModule.class;
      Stack<JavaType> stack0 = new Stack<JavaType>();
      TypeBindings typeBindings0 = TypeBindings.create((Class<?>) class0, (List<JavaType>) stack0);
      JavaType[] javaTypeArray0 = new JavaType[3];
      SimpleType simpleType0 = TypeFactory.CORE_TYPE_BOOL;
      CollectionLikeType collectionLikeType0 = new CollectionLikeType(class0, typeBindings0, (JavaType) null, javaTypeArray0, simpleType0, "-uzes+mpq[B0nEH.", (Object) null, true);
      JavaType javaType0 = typeFactory0.moreSpecificType(collectionLikeType0, javaTypeArray0[2]);
      assertFalse(javaType0.isEnumType());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.instance;
      Class<MapperFeature> class0 = MapperFeature.class;
      Class<SerializationFeature> class1 = SerializationFeature.class;
      CollectionLikeType collectionLikeType0 = typeFactory0.constructCollectionLikeType(class0, class1);
      JavaType javaType0 = typeFactory0.moreSpecificType((JavaType) null, collectionLikeType0);
      assertTrue(javaType0.isContainerType());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.instance;
      Class<MapperFeature> class0 = MapperFeature.class;
      TypeBindings typeBindings0 = TypeBindings.createIfNeeded(class0, (JavaType) null);
      ResolvedRecursiveType resolvedRecursiveType0 = new ResolvedRecursiveType(class0, typeBindings0);
      JavaType javaType0 = typeFactory0.moreSpecificType(resolvedRecursiveType0, resolvedRecursiveType0);
      assertSame(javaType0, resolvedRecursiveType0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.instance;
      Class<SerializationFeature> class0 = SerializationFeature.class;
      Class<Object> class1 = Object.class;
      JavaType[] javaTypeArray0 = new JavaType[7];
      Class<MapLikeType> class2 = MapLikeType.class;
      TypeBindings typeBindings0 = TypeBindings.createIfNeeded(class2, javaTypeArray0);
      TypeResolutionContext.Basic typeResolutionContext_Basic0 = new TypeResolutionContext.Basic(typeFactory0, typeBindings0);
      JavaType javaType0 = typeResolutionContext_Basic0.resolveType(class0);
      // Undeclared exception!
      try { 
        typeFactory0.constructGeneralizedType(javaType0, class1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Internal error: class java.lang.Object not included as super-type for [simple type, class com.fasterxml.jackson.databind.SerializationFeature]
         //
         verifyException("com.fasterxml.jackson.databind.type.TypeFactory", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.defaultInstance();
      Class<SerializationFeature> class0 = SerializationFeature.class;
      TypeBindings typeBindings0 = TypeFactory.EMPTY_BINDINGS;
      JavaType javaType0 = typeFactory0._resolveSuperClass((ClassStack) null, class0, typeBindings0);
      JavaType javaType1 = typeFactory0.constructSpecializedType(javaType0, class0);
      assertFalse(javaType0.isConcrete());
      assertFalse(javaType0.isInterface());
      assertTrue(javaType1.isFinal());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.defaultInstance();
      TypeBindings typeBindings0 = TypeFactory.EMPTY_BINDINGS;
      Class<DeserializationFeature> class0 = DeserializationFeature.class;
      SimpleType simpleType0 = TypeFactory.CORE_TYPE_CLASS;
      JavaType[] javaTypeArray0 = new JavaType[0];
      ReferenceType referenceType0 = new ReferenceType(simpleType0, simpleType0);
      MapLikeType mapLikeType0 = new MapLikeType(class0, typeBindings0, simpleType0, javaTypeArray0, simpleType0, simpleType0, referenceType0, class0, true);
      CollectionLikeType collectionLikeType0 = new CollectionLikeType(referenceType0, mapLikeType0);
      Class<MapLikeType> class1 = MapLikeType.class;
      // Undeclared exception!
      try { 
        typeFactory0.constructSpecializedType(collectionLikeType0, class1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Class com.fasterxml.jackson.databind.type.MapLikeType not subtype of [collection-like type; class java.lang.Class, contains [map-like type; class com.fasterxml.jackson.databind.DeserializationFeature, [simple type, class java.lang.Class] -> [simple type, class java.lang.Class]]]
         //
         verifyException("com.fasterxml.jackson.databind.type.TypeFactory", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.instance;
      Class<Object> class0 = Object.class;
      JavaType javaType0 = typeFactory0.constructSimpleType(class0, (JavaType[]) null);
      assertTrue(javaType0.isJavaLangObject());
      
      Class<SimpleType> class1 = SimpleType.class;
      JavaType javaType1 = typeFactory0.constructSpecializedType(javaType0, class1);
      JavaType javaType2 = typeFactory0.constructGeneralizedType(javaType1, class0);
      assertNotSame(javaType2, javaType1);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      TypeParser typeParser0 = mock(TypeParser.class, new ViolatedAssumptionAnswer());
      doReturn((TypeParser) null).when(typeParser0).withFactory(any(com.fasterxml.jackson.databind.type.TypeFactory.class));
      TypeFactory typeFactory0 = new TypeFactory(typeParser0, (TypeModifier[]) null);
      Class<EnumSet> class0 = EnumSet.class;
      SimpleType simpleType0 = TypeFactory.CORE_TYPE_STRING;
      CollectionType collectionType0 = typeFactory0.constructCollectionType((Class<? extends Collection>) class0, (JavaType) simpleType0);
      JavaType javaType0 = typeFactory0.constructSpecializedType(collectionType0, class0);
      assertTrue(javaType0.isCollectionLikeType());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.instance;
      TypeParser typeParser0 = new TypeParser(typeFactory0);
      TypeParser.MyTokenizer typeParser_MyTokenizer0 = new TypeParser.MyTokenizer("void");
      try { 
        typeParser0.parseTypes(typeParser_MyTokenizer0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Failed to parse type 'void' (remaining: ''): Unexpected end-of-string
         //
         verifyException("com.fasterxml.jackson.databind.type.TypeParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.instance;
      Class<?> class0 = typeFactory0._findPrimitive("short");
      assertEquals("short", class0.toString());
      assertNotNull(class0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.instance;
      Class<?> class0 = typeFactory0.findClass("byte");
      assertEquals("byte", class0.toString());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      TypeParser typeParser0 = mock(TypeParser.class, new ViolatedAssumptionAnswer());
      doReturn((TypeParser) null).when(typeParser0).withFactory(any(com.fasterxml.jackson.databind.type.TypeFactory.class));
      TypeModifier[] typeModifierArray0 = new TypeModifier[4];
      TypeFactory typeFactory0 = new TypeFactory(typeParser0, typeModifierArray0);
      TypeParser typeParser1 = new TypeParser(typeFactory0);
      TypeParser.MyTokenizer typeParser_MyTokenizer0 = new TypeParser.MyTokenizer("|k>*Ud1WOFh*>");
      Class<?> class0 = typeParser1.findClass("float", typeParser_MyTokenizer0);
      assertEquals("float", class0.toString());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.instance;
      ClassLoader classLoader0 = ClassLoader.getSystemClassLoader();
      TypeFactory typeFactory1 = typeFactory0.withClassLoader(classLoader0);
      Class<?> class0 = typeFactory1.findClass("com.fasterxml.jackson.databind.ser.std.TokenBufferSerializer");
      assertFalse(class0.isEnum());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.instance;
      try { 
        typeFactory0.findClass("-uzes+mpq[B0nEH.");
        fail("Expecting exception: ClassNotFoundException");
      
      } catch(ClassNotFoundException e) {
         //
         // -uzes+mpq[B0nEH/
         //
         verifyException("com.fasterxml.jackson.databind.type.TypeFactory", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Class<MapLikeType> class0 = MapLikeType.class;
      Class<?> class1 = TypeFactory.rawClass(class0);
      assertFalse(class1.isInterface());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Class<MapType> class0 = MapType.class;
      JavaType javaType0 = TypeBase._bogusSuperClass(class0);
      Class<?> class1 = TypeFactory.rawClass(javaType0);
      assertEquals(1, class1.getModifiers());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.defaultInstance();
      TypeFactory typeFactory1 = typeFactory0.withModifier((TypeModifier) null);
      assertFalse(typeFactory1.equals((Object)typeFactory0));
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.instance;
      Class<MapperFeature> class0 = MapperFeature.class;
      MapLikeType mapLikeType0 = typeFactory0.constructMapLikeType(class0, (JavaType) null, (JavaType) null);
      ArrayType arrayType0 = typeFactory0.constructArrayType((JavaType) mapLikeType0);
      assertFalse(arrayType0.useStaticType());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Class<Integer> class0 = Integer.class;
      TypeFactory typeFactory0 = TypeFactory.instance;
      Class<CollectionLikeType> class1 = CollectionLikeType.class;
      Class<AnnotationIntrospector.ReferenceProperty.Type> class2 = AnnotationIntrospector.ReferenceProperty.Type.class;
      JavaType javaType0 = TypeBase._bogusSuperClass(class2);
      MapLikeType mapLikeType0 = typeFactory0.constructMapLikeType(class1, javaType0, javaType0);
      typeFactory0.constructReferenceType(class0, mapLikeType0);
      assertTrue(javaType0.isJavaLangObject());
      assertFalse(mapLikeType0.isJavaLangObject());
      assertFalse(javaType0.isAbstract());
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.defaultInstance();
      JavaType javaType0 = typeFactory0.constructFromCanonical("long");
      assertTrue(javaType0.isPrimitive());
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      TypeParser typeParser0 = mock(TypeParser.class, new ViolatedAssumptionAnswer());
      doReturn((TypeParser) null).when(typeParser0).withFactory(any(com.fasterxml.jackson.databind.type.TypeFactory.class));
      TypeModifier[] typeModifierArray0 = new TypeModifier[4];
      TypeFactory typeFactory0 = new TypeFactory(typeParser0, typeModifierArray0);
      TypeParser typeParser1 = new TypeParser(typeFactory0);
      TypeParser.MyTokenizer typeParser_MyTokenizer0 = new TypeParser.MyTokenizer("|k>*Ud1WOFh*>");
      // Undeclared exception!
      try { 
        typeParser1.findClass("E&Ho", typeParser_MyTokenizer0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Failed to parse type '|k>*Ud1WOFh*>' (remaining: '|k>*Ud1WOFh*>'): Can not locate class 'E&Ho', problem: Class 'E&Ho.class' should be in target project, but could not be found!
         //
         verifyException("com.fasterxml.jackson.databind.type.TypeParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.instance;
      Class<Properties> class0 = Properties.class;
      // Undeclared exception!
      try { 
        typeFactory0.constructRawMapType(class0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Can not create TypeBindings for class java.util.Properties with 2 type parameters: class expects 0
         //
         verifyException("com.fasterxml.jackson.databind.type.TypeBindings", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.defaultInstance();
      Class<CollectionType>[] classArray0 = (Class<CollectionType>[]) Array.newInstance(Class.class, 6);
      TypeReference<MapType> typeReference0 = (TypeReference<MapType>) mock(TypeReference.class, new ViolatedAssumptionAnswer());
      doReturn(classArray0[0]).when(typeReference0).getType();
      // Undeclared exception!
      try { 
        typeFactory0.constructType(typeReference0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unrecognized Type: [null]
         //
         verifyException("com.fasterxml.jackson.databind.type.TypeFactory", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.instance;
      Class<SerializationFeature> class0 = SerializationFeature.class;
      Class<MapperFeature> class1 = MapperFeature.class;
      CollectionLikeType collectionLikeType0 = typeFactory0.constructCollectionLikeType(class1, class0);
      JavaType javaType0 = typeFactory0.constructGeneralizedType(collectionLikeType0, class1);
      assertTrue(javaType0.isFinal());
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.defaultInstance();
      Class<HashSet> class0 = HashSet.class;
      CollectionType collectionType0 = typeFactory0.constructCollectionType(class0, class0);
      CollectionLikeType collectionLikeType0 = typeFactory0.constructCollectionLikeType((Class<?>) class0, (JavaType) collectionType0);
      assertFalse(collectionLikeType0.equals((Object)collectionType0));
      assertEquals(1, collectionLikeType0.containedTypeCount());
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.instance;
      Class<CollectionLikeType> class0 = CollectionLikeType.class;
      CollectionLikeType collectionLikeType0 = typeFactory0.constructRawCollectionLikeType(class0);
      assertFalse(collectionLikeType0.isJavaLangObject());
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      TypeParser typeParser0 = mock(TypeParser.class, new ViolatedAssumptionAnswer());
      doReturn((TypeParser) null).when(typeParser0).withFactory(any(com.fasterxml.jackson.databind.type.TypeFactory.class));
      TypeModifier[] typeModifierArray0 = new TypeModifier[6];
      TypeFactory typeFactory0 = new TypeFactory(typeParser0, typeModifierArray0);
      typeFactory0.clearCache();
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.defaultInstance();
      Class<SerializationFeature> class0 = SerializationFeature.class;
      Class<Integer> class1 = Integer.class;
      MapLikeType mapLikeType0 = typeFactory0.constructMapLikeType(class0, class0, class1);
      assertTrue(mapLikeType0.isEnumType());
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      JsonFactory jsonFactory0 = new JsonFactory();
      ObjectMapper objectMapper0 = new ObjectMapper(jsonFactory0);
      ObjectReader objectReader0 = objectMapper0.reader();
      TypeFactory typeFactory0 = objectReader0.getTypeFactory();
      Class<Properties> class0 = Properties.class;
      JavaType javaType0 = typeFactory0.uncheckedSimpleType(class0);
      assertFalse(javaType0.isJavaLangObject());
      assertNotNull(javaType0);
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      TypeParser typeParser0 = mock(TypeParser.class, new ViolatedAssumptionAnswer());
      doReturn((TypeParser) null).when(typeParser0).withFactory(any(com.fasterxml.jackson.databind.type.TypeFactory.class));
      TypeModifier[] typeModifierArray0 = new TypeModifier[6];
      TypeFactory typeFactory0 = new TypeFactory(typeParser0, typeModifierArray0);
      Class<?> class0 = typeFactory0._findPrimitive("int");
      Class<Properties> class1 = Properties.class;
      // Undeclared exception!
      try { 
        typeFactory0.constructMapType(class1, class1, class0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Can not create TypeBindings for class java.util.Properties with 2 type parameters: class expects 0
         //
         verifyException("com.fasterxml.jackson.databind.type.TypeBindings", e);
      }
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.instance;
      Class<MapperFeature> class0 = MapperFeature.class;
      Class<Properties> class1 = Properties.class;
      JavaType[] javaTypeArray0 = new JavaType[0];
      JavaType javaType0 = typeFactory0.constructParametrizedType(class0, class1, javaTypeArray0);
      assertFalse(javaType0.isJavaLangObject());
      assertNotNull(javaType0);
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.defaultInstance();
      Class<TextNode> class0 = TextNode.class;
      TypeBindings typeBindings0 = TypeFactory.EMPTY_BINDINGS;
      JavaType[] javaTypeArray0 = typeFactory0.findTypeParameters(class0, class0, typeBindings0);
      assertEquals(0, javaTypeArray0.length);
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.instance;
      Class<LinkedList> class0 = LinkedList.class;
      CollectionType collectionType0 = typeFactory0.constructRawCollectionType(class0);
      assertFalse(collectionType0.isFinal());
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.instance;
      JavaType[] javaTypeArray0 = new JavaType[2];
      Class<ArrayType> class0 = ArrayType.class;
      Class<SerializationFeature> class1 = SerializationFeature.class;
      // Undeclared exception!
      try { 
        typeFactory0.constructSimpleType(class0, class1, javaTypeArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Can not create TypeBindings for class com.fasterxml.jackson.databind.type.ArrayType with 2 type parameters: class expects 0
         //
         verifyException("com.fasterxml.jackson.databind.type.TypeBindings", e);
      }
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      TypeFactory typeFactory0 = TypeFactory.defaultInstance();
      Class<Integer> class0 = Integer.class;
      Class<ArrayType> class1 = ArrayType.class;
      JavaType[] javaTypeArray0 = typeFactory0.findTypeParameters(class0, class1);
      assertEquals(0, javaTypeArray0.length);
  }
}
