/*
 * This file was automatically generated by EvoSuite
 * Sun Sep 20 19:38:08 GMT 2026
 */

package org.jsoup.nodes;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.nodes.Attributes;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.nodes.Node;
import org.jsoup.nodes.TextNode;
import org.jsoup.parser.Tag;
import org.jsoup.select.Elements;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Element_ESTest extends Element_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Document document0 = new Document("vc^j,-oQ");
      // Undeclared exception!
      try { 
        document0.getElementById("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // String must not be empty
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      // Undeclared exception!
      try { 
        Document.createShell("br");
       //  fail("Expecting exception: NoSuchElementException");
       // Unstable assertion
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.LinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Document document0 = new Document("^#^");
      document0.append(">?@Y;t");
      // Undeclared exception!
      try { 
        document0.html("8|$aU>SHznMwh");
       //  fail("Expecting exception: NoSuchElementException");
       // Unstable assertion
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.LinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Tag tag0 = Tag.valueOf("textarea");
      Attributes attributes0 = new Attributes();
      Element element0 = new Element(tag0, "textarea", attributes0);
      element0.hashCode();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Tag tag0 = Tag.valueOf(" b78iTJ/9S.n_=2PA.");
      TextNode textNode0 = TextNode.createFromEncoded("dg6*/|p4K", " b78iTJ/9S.n_=2PA.");
      Attributes attributes0 = textNode0.attributes();
      Element element0 = new Element(tag0, " b78iTJ/9S.n_=2PA.", attributes0);
      Element element1 = element0.toggleClass("WrIwr");
      assertSame(element1, element0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Tag tag0 = Tag.valueOf("textarea");
      Attributes attributes0 = new Attributes();
      Element element0 = new Element(tag0, "textarea", attributes0);
      element0.text("3dE2utL");
      String string0 = element0.val();
      assertEquals("3dE2utL", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Tag tag0 = Tag.valueOf(" b78iTJ/9S.n_=2PA.");
      TextNode textNode0 = TextNode.createFromEncoded("dg6*/|p4K", " b78iTJ/9S.n_=2PA.");
      Attributes attributes0 = textNode0.attributes();
      Element element0 = new Element(tag0, " b78iTJ/9S.n_=2PA.", attributes0);
      Element element1 = element0.appendElement("(u?wgv[,tZaLsdZ/1");
      Element element2 = element1.lastElementSibling();
      assertNull(element2);
      assertEquals("(u?wgv[,tzalsdz/1", element1.tagName());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Tag tag0 = Tag.valueOf("V4ALUS");
      Attributes attributes0 = new Attributes();
      Element element0 = new Element(tag0, "pahs\"WVy", attributes0);
      Element element1 = element0.previousElementSibling();
      assertNull(element1);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Tag tag0 = Tag.valueOf(" b78iTJ/9S.n_=2PA.");
      TextNode textNode0 = TextNode.createFromEncoded("dg6*/|p4K", " b78iTJ/9S.n_=2PA.");
      Attributes attributes0 = textNode0.attributes();
      Element element0 = new Element(tag0, " b78iTJ/9S.n_=2PA.", attributes0);
      Element element1 = element0.appendElement("(u?wgv[,tZaLsdZ/1");
      assertFalse(element1.equals((Object)element0));
      
      Element element2 = element1.previousElementSibling();
      assertNull(element2);
      assertEquals("(u?wgv[,tzalsdz/1", element1.tagName());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Document document0 = new Document("j9qnT");
      Element element0 = document0.nextElementSibling();
      assertNull(element0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Document document0 = new Document("^#^");
      document0.append(">?@Y;t");
      List<TextNode> list0 = document0.textNodes();
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Tag tag0 = Tag.valueOf("V4ALUS");
      Attributes attributes0 = new Attributes();
      Element element0 = new Element(tag0, "pahs\"WVy", attributes0);
      String string0 = element0.id();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Document document0 = new Document("Attributes incorrectly present on end tag");
      Elements elements0 = document0.getElementsByTag("Attributes incorrectly present on end tag");
      assertEquals(0, elements0.size());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Document document0 = new Document("value");
      // Undeclared exception!
      try { 
        document0.getElementsMatchingText("k?R&]U;)0z");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Pattern syntax error: k?R&]U;)0z
         //
         verifyException("org.jsoup.nodes.Element", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Document document0 = new Document("0JoMBb|@wixwkSW|J5");
      Document document1 = (Document)document0.removeClass("pattern syntax error: ");
      assertEquals(Document.QuirksMode.noQuirks, document1.quirksMode());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Document document0 = new Document("E'A2ijc}-n\"(kJGe-P");
      String string0 = document0.ownText();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Document document0 = new Document("/BSfC\"OoX@MK'0uu");
      // Undeclared exception!
      try { 
        document0.getElementsByAttributeValueNot("/BSfC\"OoX@MK'0uu", "");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // String must not be empty
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Document document0 = new Document("0JoMBb|@wixwkSW|J5");
      Document document1 = document0.clone();
      Element element0 = document1.removeClass("pattern syntax error: ");
      assertNotSame(element0, document0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Tag tag0 = Tag.valueOf("value");
      Attributes attributes0 = new Attributes();
      Element element0 = new Element(tag0, "7!Yp!?,@a3m", attributes0);
      Elements elements0 = element0.getElementsContainingText("value");
      // Undeclared exception!
      try { 
        element0.insertChildren(73, elements0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Insert position out of bounds.
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Document document0 = new Document("s/");
      Elements elements0 = document0.getElementsByClass("3xdl dda+f_igc~");
      assertEquals(0, elements0.size());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Document document0 = new Document("value");
      Elements elements0 = document0.getElementsByAttributeValueEnding("Tg]oBlpn|tbda[i`7s", "Tg]oBlpn|tbda[i`7s");
      assertTrue(elements0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Document document0 = new Document("E'A2ijc}-n\"(kJGe-P");
      // Undeclared exception!
      try { 
        document0.getElementsByAttributeValueMatching(" ", "E'A2ijc}-n\"(kJGe-P");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Pattern syntax error: E'A2ijc}-n\"(kJGe-P
         //
         verifyException("org.jsoup.nodes.Element", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Document document0 = new Document("^#^");
      Element element0 = document0.val("zlA#]G{m><");
      assertEquals("^#^", element0.baseUri());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Document document0 = new Document("QY");
      // Undeclared exception!
      try { 
        document0.wrap("QY");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.nodes.Node", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Document document0 = new Document("");
      // Undeclared exception!
      try { 
        document0.after("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Object must not be null
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Tag tag0 = Tag.valueOf("html");
      Attributes attributes0 = new Attributes();
      Element element0 = new Element(tag0, "html", attributes0);
      Element element1 = element0.prepend("html");
      assertEquals("html", element1.nodeName());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Document document0 = new Document("Attributes incorrectly present on end tag");
      Element element0 = document0.addClass("Attributes incorrectly present on end tag");
      assertSame(document0, element0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Document document0 = new Document("ins");
      document0.tagName("6SZ9jNbAOB!4kwk%B");
      assertEquals("6sz9jnbaob!4kwk%b", document0.tagName());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Document document0 = new Document("/BSfC\"OoX@MK'0uu");
      Element element0 = document0.prependText("Tag name must not be empty.");
      assertFalse(element0.isBlock());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Tag tag0 = Tag.valueOf("textarea");
      Attributes attributes0 = new Attributes();
      Element element0 = new Element(tag0, "textarea", attributes0);
      Element element1 = element0.text("3dE2utL");
      StringBuilder stringBuilder0 = new StringBuilder();
      Document.OutputSettings document_OutputSettings0 = new Document.OutputSettings();
      element1.parentNode = (Node) element0;
      element1.outerHtmlTail(stringBuilder0, 210, document_OutputSettings0);
      element0.outerHtmlHead(stringBuilder0, 64, document_OutputSettings0);
      assertEquals("</textarea><textarea>", stringBuilder0.toString());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Document document0 = new Document("         ");
      // Undeclared exception!
      try { 
        document0.child(1);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 1, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Document document0 = new Document("Children collection to be inserted must not be null.");
      // Undeclared exception!
      try { 
        document0.normalise();
       //  fail("Expecting exception: NoSuchElementException");
       // Unstable assertion
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.LinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Document document0 = new Document("s/");
      Document document1 = (Document)document0.appendText("html");
      assertEquals(Document.QuirksMode.noQuirks, document1.quirksMode());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Document document0 = new Document("#@oot");
      // Undeclared exception!
      try { 
        document0.html("Cd}uH$sqr} rjn(mi");
       //  fail("Expecting exception: NoSuchElementException");
       // Unstable assertion
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.LinkedList", e);
      }
  }
}
