/*
 * This file was automatically generated by EvoSuite
 * Sun Sep 20 23:11:46 GMT 2026
 */

package org.jsoup.nodes;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Entities;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Entities_ESTest extends Entities_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      StringBuilder stringBuilder0 = new StringBuilder((CharSequence) "US-ASCII");
      Document.OutputSettings document_OutputSettings0 = new Document.OutputSettings();
      document_OutputSettings0.charset("US-ASCII");
      Entities.escape(stringBuilder0, "US-ASCII", document_OutputSettings0, true, true, true);
      assertEquals("US-ASCIIUS-ASCII", stringBuilder0.toString());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      StringBuilder stringBuilder0 = new StringBuilder("notelement");
      Document.OutputSettings document_OutputSettings0 = new Document.OutputSettings();
      Entities.escape(stringBuilder0, "width must be > 0", document_OutputSettings0, true, true, true);
      assertEquals("notelementwidth must be > 0", stringBuilder0.toString());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      StringBuilder stringBuilder0 = new StringBuilder();
      Document.OutputSettings document_OutputSettings0 = new Document.OutputSettings();
      Entities.escape(stringBuilder0, "<!", document_OutputSettings0, true, true, true);
      assertEquals("<!", stringBuilder0.toString());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      StringBuilder stringBuilder0 = new StringBuilder("+jj ({K");
      Document.OutputSettings document_OutputSettings0 = new Document.OutputSettings();
      Entities.escape(stringBuilder0, "Fyw<M", document_OutputSettings0, false, false, true);
      assertEquals("+jj ({KFyw&lt;M", stringBuilder0.toString());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Document.OutputSettings document_OutputSettings0 = new Document.OutputSettings();
      StringBuilder stringBuilder0 = new StringBuilder((CharSequence) "?}Py&gt;,Ft/");
      Entities.escape(stringBuilder0, "?}Py&gt;,Ft/", document_OutputSettings0, false, false, false);
      assertEquals("?}Py&gt;,Ft/?}Py&amp;gt;,Ft/", stringBuilder0.toString());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Document.OutputSettings document_OutputSettings0 = new Document.OutputSettings();
      StringBuilder stringBuilder0 = new StringBuilder(")'A[S");
      Entities.escape(stringBuilder0, "]{,?\"", document_OutputSettings0, false, false, false);
      assertEquals(")'A[S]{,?\"", stringBuilder0.toString());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      StringBuilder stringBuilder0 = new StringBuilder(2168);
      Document.OutputSettings document_OutputSettings0 = new Document.OutputSettings();
      Entities.escape(stringBuilder0, " ", document_OutputSettings0, true, true, true);
      assertEquals("", stringBuilder0.toString());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      StringBuilder stringBuilder0 = new StringBuilder("+jj ({K");
      Document.OutputSettings document_OutputSettings0 = new Document.OutputSettings();
      Entities.escape(stringBuilder0, "+jj ({K", document_OutputSettings0, true, true, false);
      assertEquals("+jj ({K+jj ({K", stringBuilder0.toString());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      boolean boolean0 = Entities.isBaseNamedEntity("amp");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      boolean boolean0 = Entities.isBaseNamedEntity("updownarrow");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      boolean boolean0 = Entities.isNamedEntity("updownarrow");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      boolean boolean0 = Entities.isNamedEntity("cWrOu\u0002Bg>G?an{~B{0");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Document.OutputSettings document_OutputSettings0 = new Document.OutputSettings();
      String string0 = Entities.escape("?}Py>,Ft/", document_OutputSettings0);
      assertEquals("?}Py&gt;,Ft/", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      String string0 = Entities.unescape(")'A[S");
      assertEquals(")'A[S", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Character character0 = Entities.getCharacterByName((String) null);
      assertNull(character0);
  }
}
